/** @type {import('tailwindcss').Config} */
export default {
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'tertiary-container': '#aa2b00',
        'surface-bright': '#f9f9ff',
        'surface-variant': '#dce2f3',
        'on-secondary-container': '#62646a',
        'surface-container-highest': '#dce2f3',
        surface: '#f9f9ff',
        'inverse-primary': '#bdc2ff',
        'on-secondary-fixed': '#191c21',
        'primary-container': '#2b3ef0',
        'on-tertiary-fixed': '#3b0900',
        'surface-dim': '#d3daea',
        'surface-container-lowest': '#ffffff',
        'on-error': '#ffffff',
        primary: '#001bd4',
        'on-primary-fixed': '#000866',
        secondary: '#5c5e64',
        background: '#f9f9ff',
        'inverse-surface': '#2a313d',
        'inverse-on-surface': '#ebf1ff',
        'on-surface-variant': '#444556',
        'on-tertiary-fixed-variant': '#872000',
        'error-container': '#ffdad6',
        'on-primary': '#ffffff',
        outline: '#757688',
        'surface-container': '#e7eefe',
        'tertiary-fixed': '#ffdbd1',
        'surface-container-high': '#e2e8f8',
        'on-surface': '#151c27',
        'on-primary-fixed-variant': '#021ede',
        'tertiary-fixed-dim': '#ffb5a0',
        'on-secondary': '#ffffff',
        error: '#ba1a1a',
        'surface-container-low': '#f0f3ff',
        tertiary: '#811e00',
        'on-error-container': '#93000a',
        'on-background': '#151c27',
        'secondary-container': '#e1e2e9',
        'on-tertiary-container': '#ffc5b5',
        'on-primary-container': '#cbcfff',
        'primary-fixed': '#dfe0ff',
        'outline-variant': '#c5c5d9',
        'secondary-fixed-dim': '#c5c6cd',
        'on-secondary-fixed-variant': '#44474c',
        'surface-tint': '#3143f4',
        'on-tertiary': '#ffffff',
        'secondary-fixed': '#e1e2e9',
        'primary-fixed-dim': '#bdc2ff',
      },
      fontFamily: {
        caption: ['Inter', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'label-md': ['Inter', 'sans-serif'],
        'headline-md': ['Manrope', 'sans-serif'],
        'headline-xl': ['Manrope', 'sans-serif'],
        'headline-lg-mobile': ['Manrope', 'sans-serif'],
        'headline-lg': ['Manrope', 'sans-serif'],
      },
      fontSize: {
        caption: ['12px', { lineHeight: '16px', fontWeight: '500' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.05em', fontWeight: '600' }],
        'headline-md': ['24px', { lineHeight: '32px', fontWeight: '600' }],
        'headline-xl': ['40px', { lineHeight: '48px', letterSpacing: '-0.02em', fontWeight: '800' }],
        'headline-lg-mobile': ['24px', { lineHeight: '32px', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '700' }],
      },
      spacing: {
        'stack-sm': '8px',
        'margin-mobile': '16px',
        'container-max-width': '1200px',
        'sidebar-width': '280px',
        'stack-md': '16px',
        'stack-lg': '32px',
        gutter: '24px',
      },
    },
  },
  plugins: [],
}
